agent_name: get_price_agent
author: valory
version: 0.1.0
license: Apache-2.0
description: A price fetching agent.
aea_version: ">=1.19.0, <2.0.0"
fingerprint:
  __init__.py: bafybei0000000000000000000000000000000000000000000000000000
fingerprint_ignore_patterns: []
default_ledger: ethereum
required_ledgers:
  - ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: "[%(asctime)s] [%(levelname)s] %(message)s"
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: ${LOG_LEVEL:str:INFO}
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
        - logfile
        - console
      propagate: true
skill_exception_policy: stop_and_exit
dependencies:
  open-aea-ledger-ethereum:
    version: ==1.53.0
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/learning_chained_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:http://localhost:8545}
      chain_id: ${int:31337}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
    gnosis:
      address: ${str:http://localhost:8545}
      chain_id: ${int:1337}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
    - uri: ${str:acn.staging.autonolas.tech:9005}
      public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
  - identifier: acn
    ledger_id: ethereum
    message_format: "{public_key}"
    not_after: "2023-01-01"
    not_before: "2022-01-01"
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
    save_path: .certs/acn_cosmos_11000.txt
---
public_id: valory/http_server:0.22.0:bafybeicblltx7ha3ulthg7bzfccuqqyjmihhrvfeztlgrlcoxhr7kf6nbq
type: connection
config:
  host: 0.0.0.0
  target_skill_id: valory/learning_chained_abci:0.1.0
---
public_id: valory/learning_chained_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: ${str:/logs}
  params:
    args:
      cleanup_history_depth: 1
      cleanup_history_depth_current: null
      drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
      genesis_config:
        genesis_time: "2022-09-26T00:00:00.000000000Z"
        chain_id: chain-c4daS1
        consensus_params:
          block:
            max_bytes: "22020096"
            max_gas: "-1"
            time_iota_ms: "1000"
          evidence:
            max_age_num_blocks: "100000"
            max_age_duration: "172800000000000"
            max_bytes: "1048576"
          validator:
            pub_key_types:
              - ed25519
          version: {}
        voting_power: "10"
      keeper_timeout: 30.0
      max_attempts: 10
      max_healthcheck: 120
      multisend_address: ${str:0x0000000000000000000000000000000000000000}
      termination_sleep: ${int:900}
      init_fallback_gas: 0
      keeper_allowed_retries: 3
      reset_pause_duration: ${int:10}
      on_chain_service_id: ${int:null}
      reset_tendermint_after: ${int:10}
      retry_attempts: 400
      retry_timeout: 3
      request_retry_delay: 1.0
      request_timeout: 10.0
      round_timeout_seconds: 30.0
      service_id: learning
      service_registry_address: ${str:null}
      setup:
        all_participants: ${list:["0x615d3278680337e2D39C3bc5042D959C7938B917"]}
        safe_contract_address: ${str:0x5C5b146905c11Ee1fE7260c0338b52DCA9582a13}
        consensus_threshold: ${int:null}
      share_tm_config_on_startup: ${bool:false}
      sleep_time: 1
      tendermint_check_sleep_delay: 3
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_max_retries: 5
      tendermint_url: ${str:http://localhost:26657}
      tendermint_p2p_url: ${str:localhost:26656}
      use_termination: ${bool:false}
      tx_timeout: 10.0
      validate_timeout: 1205
      finalize_timeout: 60.0
      history_check_timeout: 1205
      use_slashing: ${bool:false}
      slash_cooldown_hours: ${int:3}
      slash_threshold_amount: ${int:10000000000000000}
      light_slash_unit_amount: ${int:5000000000000000}
      serious_slash_unit_amount: ${int:8000000000000000}
      multisend_batch_size: ${int:50}
      ipfs_address: ${str:https://gateway.autonolas.tech/ipfs/}
      coingecko_price_template: ${str:https://api.coingecko.com/api/v3/simple/price?ids=autonolas&vs_currencies=usd&x_cg_demo_api_key={api_key}}
      coingecko_api_key: ${str:null}
      default_chain_id: ${str:gnosis}
      termination_from_block: ${int:34088325}
      transfer_target_address: ${str:0x615d3278680337e2D39C3bc5042D959C7938B917}
